  version: '3'

  services:
    web:
      build: .
      command: python3 manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/code
      ports:
        - "8000:8000"
      depends_on:
        - db
    
    db:
      image: postgres:latest
      environment:
       - POSTGRES_DB=wechat
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=password
      
      ports:
        - "5433:5432"