# Generated by Django 4.2.5 on 2023-10-05 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='messaege',
            new_name='message',
        ),
    ]
